### ISSUE TITLE
Is there any looped video collection?

### ISSUE THREAD

**Issue by Jimmm** [thatcluda/Eneko#3]
Great tweak, I use my own looped fotos. But I find videos from the previews are very cute. Where can I get them, please? For example this one:
![image](https://user-images.githubusercontent.com/960136/160024511-713e45ea-9401-4c3a-88e5-d90ba8740c17.png)

**Comment by thatcluda** [comment]
there’s not and there’s not going to be one

that preview can be found on [mylivewallpapers](https://mylivewallpapers.com/category/anime/)
